# Generated by Django 4.0.4 on 2022-05-09 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0003_remove_message_receiver_remove_message_sender_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='market',
            field=models.ForeignKey(default=1, help_text='غرفه دار', on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to=settings.AUTH_USER_MODEL, verbose_name='دریافت کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(default=1, help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[['user', 'کاربر'], ['market', 'فروشنده']], default='market', max_length=255, verbose_name='فرستنده'),
            preserve_default=False,
        ),
    ]
