# Generated by Django 4.0.4 on 2022-05-09 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0004_remove_chat_receiver_remove_chat_sender_chat_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to=settings.AUTH_USER_MODEL, verbose_name='غرفه دار'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
