# Generated by Django 4.0.4 on 2022-05-09 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_market_instagram_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0005_alter_chat_market_alter_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market', verbose_name='غرفه '),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[['user', 'کاربر'], ['market', 'غرفه']], max_length=255, verbose_name='فرستنده'),
        ),
    ]
