# Generated by Django 4.0.4 on 2022-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_chat_market_alter_chat_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط مخاطب'),
        ),
    ]
