# Generated by Django 4.0.4 on 2022-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_album_product_image_product_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='قیمت به تومان'),
        ),
    ]
