# Generated by Django 4.0.4 on 2022-05-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_market_instagram_address_and_more'),
        ('product', '0006_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='market_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.market', verbose_name='غرفه'),
            preserve_default=False,
        ),
    ]
