# Generated by Django 4.0.4 on 2022-05-14 11:10

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_preperation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=1, default=1, max_digits=2, verbose_name='میانگین امتیاز')),
                ('sales_amount', models.IntegerField(default=0, help_text='اتوماتیک', verbose_name='مجموع فروش')),
                ('sales_count', models.IntegerField(default=0, help_text='اتوماتیک', verbose_name='تعداد فروش')),
                ('count', models.IntegerField(default=1, verbose_name='تعداد موجود ')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='قیمت به تومان')),
                ('active', models.BooleanField(default=True, verbose_name='نمایش در وبسایت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=product.models.get_file_path_for_template_image, verbose_name='َتصویر 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=product.models.get_file_path_for_template_image, verbose_name='َتصویر 2')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قالب محصول',
                'verbose_name_plural': 'قالب محصولات',
            },
        ),
    ]
