# Generated by Django 4.0.4 on 2022-05-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_producttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='city_id',
        ),
    ]
