# Generated by Django 4.0.4 on 2022-05-15 18:48

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to=product.models.get_file_path_for_image, verbose_name='َتصویر شاخص'),
            preserve_default=False,
        ),
    ]
