# Generated by Django 4.0.4 on 2022-05-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='در صورت رد تایید ، دلیل را در اینجا بنویسید تا برای کاربر نمایش داده شود.', null=True, verbose_name='دلیل رد اطلاعات'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='pending', max_length=255, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='OffCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مقدار به درصد')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('template_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.producttemplate', verbose_name='قالب کارت مربوطه')),
            ],
            options={
                'verbose_name': 'تخفیف محصول',
                'verbose_name_plural': 'تخفیف محصول',
            },
        ),
    ]
