# Generated by Django 4.0.4 on 2022-05-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_reject_reason_product_status_offcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_description',
            field=models.CharField(default='', max_length=255, verbose_name='در صورتی که نیاز به دریافت اطلاعات بیشتر از سمت خریدار را دارید ، عنوان درخواست را اینجا وارد نمایید'),
            preserve_default=False,
        ),
    ]
