# Generated by Django 4.0.4 on 2022-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_extra_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='در صورتی که نیاز به دریافت اطلاعات بیشتر از سمت خریدار را دارید ، عنوان درخواست را اینجا وارد نمایید'),
        ),
    ]
