# Generated by Django 4.0.4 on 2022-05-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_extra_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('rejected', 'مشکل در تایید'), ('confirmed', 'تایید شده'), ('hidden', 'مخفی شده')], default='pending', max_length=255, verbose_name='وضعیت'),
        ),
    ]
