# Generated by Django 4.0.4 on 2022-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visibility_status',
            field=models.BooleanField(default=False, verbose_name='نمایش در وبسایت'),
        ),
    ]
