# Generated by Django 4.0.4 on 2022-05-05 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0002_alter_city_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام بانک')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'بانک',
                'verbose_name_plural': 'بانک ها',
            },
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کسب و کار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع کسب و کار',
                'verbose_name_plural': 'انواع کسب و کار',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام فروشگاه')),
                ('message', models.TextField(verbose_name='متن پیام غرفه دار')),
                ('username', models.CharField(help_text='مسیر دسترسی به فروشگاه شما در مجموعه خاتون زیبا که آدرس مستقیم ورود به فروشگاه شما خواهد بود.', max_length=255, unique=True, verbose_name='آدرس فروشگاه')),
                ('about', models.TextField(verbose_name='درباره فروشگاه')),
                ('address', models.TextField(verbose_name='آدرس فروشگاه')),
                ('telegram_address', models.TextField(blank=True, null=True, verbose_name='آدرس تلگرام')),
                ('instagram_address', models.TextField(blank=True, null=True, verbose_name='آدرس اینستاگرام')),
                ('website_address', models.TextField(blank=True, null=True, verbose_name='آدرس وبسایت')),
                ('mobile', models.CharField(max_length=255, verbose_name='شماره همراه')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='تلفن ثابت')),
                ('shaba', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره شبا')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=market.models.get_cover_path, verbose_name='تصویر کاور')),
                ('image', models.ImageField(blank=True, null=True, upload_to=market.models.get_image_path, verbose_name='تصویر شاخص')),
                ('document', models.ImageField(blank=True, null=True, upload_to=market.models.get_document_path, verbose_name='تصویر مدارک')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.bank', verbose_name='بانک')),
                ('business_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.businesstype', verbose_name='نوع کسب و کار')),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='state.city', verbose_name='شهر')),
                ('province_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='state.province', verbose_name='استان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'غرفه',
                'verbose_name_plural': 'غرفه ها',
            },
        ),
    ]
