# Generated by Django 4.0.4 on 2022-05-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_shippingmethods'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='status',
            field=models.CharField(choices=[['authenticated', 'احراز هویت شده'], ['pending', 'در حال بررسی مدارک'], ['starter', 'در حال تکمیل مدارک'], ['rejected', 'رد شده']], default='starter', max_length=32, verbose_name='وضعیت غرفه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='status_message',
            field=models.TextField(blank=True, help_text='در صورتی که برای مثال نواقصی در مدارک موجود بود از این طریق می توانید کاربر را مطلع سازید.', verbose_name='پیام وضعیت غرفه'),
        ),
    ]
