# Generated by Django 4.0.4 on 2022-05-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_market_status_market_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='market',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='درباره فروشگاه'),
        ),
        migrations.AlterField(
            model_name='market',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس فروشگاه'),
        ),
        migrations.AlterField(
            model_name='market',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='متن پیام غرفه دار'),
        ),
        migrations.AlterField(
            model_name='market',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='market',
            name='username',
            field=models.CharField(blank=True, help_text='مسیر دسترسی به فروشگاه شما در مجموعه خاتون زیبا که آدرس مستقیم ورود به فروشگاه شما خواهد بود.', max_length=255, null=True, unique=True, verbose_name='آدرس فروشگاه'),
        ),
    ]
