# Generated by Django 4.0.1 on 2022-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_market_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='company_name',
            field=models.CharField(blank=True, help_text='در صورت حقوقی بودن', max_length=255, null=True, verbose_name='نام کامل شرکت'),
        ),
        migrations.AddField(
            model_name='market',
            name='financial_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد اقتصادی'),
        ),
        migrations.AddField(
            model_name='market',
            name='register_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره ثبت'),
        ),
        migrations.AddField(
            model_name='market',
            name='second_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره اضطراری'),
        ),
    ]
