# Generated by Django 4.1 on 2022-09-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_market_company_name_market_financial_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="marketer_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نام غرفه\u200cدار"
            ),
        ),
    ]
