# Generated by Django 4.0.4 on 2022-05-24 10:20

import config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='تایتل صفحه اصلی')),
                ('index_description', models.TextField(blank=True, null=True, verbose_name='متا دسکریپشن صفحه صالی ')),
                ('index_keywords', models.TextField(blank=True, null=True, verbose_name='متا کیوردز صفحه اصلی')),
                ('index_main_image', models.ImageField(upload_to=config.models.get_file_path_for_avatar, verbose_name='عکس بزرگ صفحه اصلی')),
                ('index_main_image_1', models.ImageField(upload_to=config.models.get_file_path_for_avatar, verbose_name='عکس کوچک اول صفحه اصلی')),
                ('index_main_image_2', models.ImageField(upload_to=config.models.get_file_path_for_avatar, verbose_name='عکس کوچک دوم صفحه اصلی')),
                ('shop_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='تایتل صفحه اصلی فروشگاه')),
                ('shop_description', models.TextField(blank=True, null=True, verbose_name='متا دسکریپشن صفحه اصلی فروشگاه ')),
                ('shop_keywords', models.TextField(blank=True, null=True, verbose_name='متا کیوردز صفحه اصلی فروشگاه')),
                ('blog_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='تایتل صفحه اصلی بلاگ')),
                ('blog_description', models.TextField(blank=True, null=True, verbose_name='متا دسکریپشن صفحه اصلی بلاگ ')),
                ('blog_keywords', models.TextField(blank=True, null=True, verbose_name='متا کیوردز صفحه اصلی بلاگ')),
            ],
            options={
                'verbose_name': 'تنظیمات وبسایت',
                'verbose_name_plural': 'تنظیمات وبسایت',
            },
        ),
    ]
