# Generated by Django 4.0.4 on 2022-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_websiteconfiguration_index_main_image_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfiguration',
            name='index_main_image_1_link',
            field=models.TextField(default='#', verbose_name='لینک عکس کوچک اول صفحه اصلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='index_main_image_2_link',
            field=models.TextField(default='#', verbose_name='لینک عکس کوچک دوم صفحه اصلی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='websiteconfiguration',
            name='index_main_image_link',
            field=models.TextField(verbose_name='لینک عکس بزرگ صفحه اصلی'),
        ),
    ]
