# Generated by Django 4.0.4 on 2022-05-08 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name=' موجودی به تومان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول ها',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name=' مقدار تراکنش')),
                ('type', models.CharField(choices=[('bank_deposit', 'واریز بانکی'), ('point_deposit', 'تبدیل امتیاز'), ('purchase_withdraw', 'خرید کارت')], max_length=20, verbose_name='نوع تراکنش ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('cancel', 'لغو شده'), ('done', 'پرداخت شده')], max_length=7, verbose_name='وضعیت')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت انتخابی')),
                ('pay_card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت واریزی')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش  کیف پول',
                'verbose_name_plural': 'تراکنش های کیف پول',
                'ordering': ['-created'],
            },
        ),
    ]
