# Generated by Django 4.0.4 on 2022-05-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ویژگی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تایرخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'مقدار ویژگی',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='مقدار ویژگی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تایرخ بروزرسانی')),
                ('attribute_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute', verbose_name='مشخصه')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'مقدار ویژگی',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('attribute_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute', verbose_name='مشخصه')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('value_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.attributevalue', verbose_name='مقدار مشخصه')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی محصولات',
            },
        ),
    ]
