# Generated by Django 4.0.4 on 2022-05-05 21:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': ' ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'مقادیر ویژگی'},
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='اگر از نوع رنگ است ، رنگ دقیق آن را نیز انتخاب نمایید', image_field=None, max_length=18, null=True, samples=None, verbose_name='مقدار رنگ'),
        ),
    ]
