# Generated by Django 4.0.4 on 2022-05-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_producttemplate'),
        ('attribute', '0003_productattribute_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_template_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.producttemplate', verbose_name='قالب محصول'),
        ),
    ]
