# Generated by Django 4.0.4 on 2022-05-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_producttemplate'),
        ('attribute', '0004_remove_productattribute_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product_template_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.producttemplate', verbose_name='قالب محصول'),
        ),
    ]
