# Generated by Django 4.0.4 on 2022-05-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0006_remove_productattribute_value_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='value_ids',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='key',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='کلید خصیصه'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.attributevalue', verbose_name='مقدار مشخصه'),
        ),
    ]
