# Generated by Django 4.0.4 on 2022-05-21 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0011_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مقدار به درصد')),
                ('expire', models.PositiveSmallIntegerField(verbose_name='اعتبار به روز')),
                ('uid', models.CharField(default='3UULAZ3B6U', max_length=10, verbose_name='کد')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تایرخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'سبد خرید'), ('cancel', 'لغو شده'), ('pending', 'در حال ارسال'), ('pending_auth', 'در حال بررسی'), ('done', 'موفق')], max_length=30, verbose_name='وضعیت')),
                ('is_satisfied', models.BooleanField(default=True, verbose_name='آماده فروش')),
                ('order_code', models.CharField(blank=True, help_text='اتوماتیک', max_length=10, null=True, verbose_name='شماره سفارش')),
                ('purchased_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انجام پرداخت ')),
                ('points', models.IntegerField(default=0, help_text='امتیاز کسب شده از خرید', verbose_name='امتیاز')),
                ('points_converted', models.BooleanField(default=False, verbose_name='امتیازات به کیف پول انتقال یافته')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('discount_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.discount', verbose_name='کد تخفیف اعمال شده')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تایرخ بروزرسانی')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='سفارش مربوطه ')),
                ('product_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('template_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.producttemplate', verbose_name='قالب محصول')),
            ],
            options={
                'verbose_name': 'خط سفارش',
                'verbose_name_plural': 'خط سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.discount', verbose_name='کد تخفیف')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده کننده کد تخفیف ',
                'verbose_name_plural': 'استفاده کننده های کد تخفیف',
            },
        ),
    ]
