# Generated by Django 4.0.4 on 2022-05-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_market_national_code_alter_market_about_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='market_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.market', verbose_name='فروشگاه'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='DPC53CORZ3', max_length=10, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'سبد خرید'), ('cancel', 'لغو شده'), ('pending', 'در حال آماده سازی'), ('done', 'موفق')], max_length=30, verbose_name='وضعیت'),
        ),
    ]
