# Generated by Django 4.0.4 on 2022-05-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderline_market_id_alter_discount_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='643NPRX860', max_length=10, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'سبد خرید'), ('cancel', 'لغو شده'), ('decomposed', 'تفکیک شده'), ('pending', 'در حال آماده سازی'), ('done', 'موفق')], max_length=30, verbose_name='وضعیت'),
        ),
    ]
