# Generated by Django 4.0.4 on 2022-05-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_discount_uid_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='سفارش مادر'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='KYGLPCU95A', max_length=10, verbose_name='کد'),
        ),
    ]
