# Generated by Django 4.0.4 on 2022-05-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_image'),
        ('order', '0004_order_original_order_id_alter_discount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='JJ8OUJIZSX', max_length=10, verbose_name='کد'),
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together={('order_id', 'product_id')},
        ),
    ]
