# Generated by Django 4.0.4 on 2022-05-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_image'),
        ('market', '0005_market_national_code_alter_market_about_and_more'),
        ('order', '0005_alter_discount_uid_alter_orderline_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='GCMJ3KIJLB', max_length=10, verbose_name='کد'),
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together={('order_id', 'product_id', 'market_id')},
        ),
    ]
