# Generated by Django 4.0.4 on 2022-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_discount_uid_alter_orderline_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='K8GB4MHAAR', max_length=10, verbose_name='کد'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order_id', 'product_id', 'market_id'), name='unique_migration_host_combination'),
        ),
    ]
