# Generated by Django 4.0.4 on 2022-05-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderline_unique_together_alter_discount_uid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderline',
            name='unique_migration_host_combination',
        ),
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='35E6MYQ4UL', max_length=10, verbose_name='کد'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order_id', 'product_id', 'market_id', 'template_id'), name='unique_migration_host_combination'),
        ),
    ]
