# Generated by Django 4.0.4 on 2022-05-23 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_image'),
        ('order', '0008_remove_orderline_unique_migration_host_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='06G7ULDP90', max_length=10, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول'),
        ),
    ]
