# Generated by Django 4.0.4 on 2022-05-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_orderline_unique_migration_host_combination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت ارسال'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='TCX82JE77M', max_length=10, verbose_name='کد'),
        ),
    ]
