# Generated by Django 4.0.4 on 2022-05-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_active'),
        ('order', '0011_order_delivery_date_alter_discount_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='آدرس انتخابی'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='2BLSDSNXTI', max_length=10, verbose_name='کد'),
        ),
    ]
