# Generated by Django 4.0.4 on 2022-05-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderline_count_alter_discount_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='sub_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_lines', to='order.order', verbose_name='زیر سفارش مربوطه '),
        ),
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='3HM9D3BDLY', max_length=10, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='original_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='order.order', verbose_name='سفارش مادر'),
        ),
    ]
