# Generated by Django 4.0.4 on 2022-05-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_orderline_sub_order_id_alter_discount_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='CZVQBUOWA4', max_length=10, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='sub_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_lines', to='order.order', verbose_name='زیر سفارش مربوطه '),
        ),
    ]
