# Generated by Django 4.0.4 on 2022-05-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_discount_uid_alter_orderline_sub_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='LBDVO13OAL', max_length=10, verbose_name='کد'),
        ),
    ]
