# Generated by Django 4.0.4 on 2022-05-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_discount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='8P1T841D37', max_length=10, verbose_name='کد'),
        ),
    ]
