# Generated by Django 4.0.1 on 2022-09-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_discount_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='uid',
            field=models.CharField(default='8OED98DS7Q', max_length=10, verbose_name='کد'),
        ),
    ]
