# Generated by Django 4.1 on 2023-11-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0030_alter_discount_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="uid",
            field=models.CharField(
                default="G06JHCI8EF", max_length=10, verbose_name="کد"
            ),
        ),
    ]
